apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenantnetworks.danm.io
spec:
  scope: Namespaced
  group: danm.io
  version: v1
  names:
    kind: TenantNetwork
    plural: tenantnetworks
    singular: tenantnetwork
    shortNames:
    - tn
    - tnet
    categories:
    - all
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            NetworkID:
              type: string
            NetworkType:
              type: string
            Options:
              properties:
                cidr:
                  oneOf:
                  - type: string
                    maxLength: 0
                  - type: string
                    format: cidr
                    pattern: '^\d+\.'
                allocation_pool:
                  properties:
                    start:
                      oneOf:
                      - type: string
                        maxLength: 0
                      - type: string
                        format: ipv4
                    end:
                      oneOf:
                      - type: string
                        maxLength: 0
                      - type: string
                        format: ipv4
                    lastIp:
                      oneOf:
                      - type: string
                        maxLength: 0
                      - type: string
                        format: cidr
                        pattern: '^\d+\.'
                container_prefix:
                  type: string
                host_device:
                  type: string
                device_pool:
                  type: string
                vxlan:
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 16777214
                vlan:
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 4094
                rt_tables:
                  type: integer
                  format: int32
                  minimum: 0
                  maximum: 255
                net6:
                  oneOf:
                  - type: string
                    maxLength: 0
                  - type: string
                    format: cidr
                    pattern: ':'
                allocation_pool_v6:
                  properties:
                    start:
                      oneOf:
                      - type: string
                        maxLength: 0
                      - type: string
                        format: ipv6
                    end:
                      oneOf:
                      - type: string
                        maxLength: 0
                      - type: string
                        format: ipv6
                    lastIp:
                      oneOf:
                      - type: string
                        maxLength: 0
                      - type: string
                        format: cidr
                        pattern: ':'
                    cidr:
                      oneOf:
                      - type: string
                        maxLength: 0
                      - type: string
                        format: cidr
                        pattern: ':'
                routes:
                  type: object
                routes6:
                  type: object
