apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: danmeps.danm.io
spec:
  scope: Namespaced
  group: danm.io
  version: v1
  names:
    kind: DanmEp
    plural: danmeps
    singular: danmep
    shortNames:
    - de
    - dep
