# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: danmeps.danm.k8s.io
spec:
  scope: Namespaced
  group: danm.k8s.io
  version: v1
  names:
    kind: DanmEp
    plural: danmeps
    singular: danmep
    shortNames:
    - de
    - dep
