# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: management
  namespace: example-vnf
spec:
  NetworkID: management
  NetworkType: flannel
