apiVersion: v1
kind: ServiceAccount
metadata:
  name: svcwatcher
  namespace: kube-system
  labels:
      kubernetes.io/cluster-service: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:svcwatcher
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - get
  - update
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "danm.k8s.io"
  resources:
  - danmeps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:svcwatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:svcwatcher
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: svcwatcher

