/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	danmv1 "github.com/nokia/danm/crd/apis/danm/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTenantConfigs implements TenantConfigInterface
type FakeTenantConfigs struct {
	Fake *FakeDanmV1
}

var tenantconfigsResource = schema.GroupVersionResource{Group: "danm.k8s.io", Version: "v1", Resource: "tenantconfigs"}

var tenantconfigsKind = schema.GroupVersionKind{Group: "danm.k8s.io", Version: "v1", Kind: "TenantConfig"}

// Get takes name of the tenantConfig, and returns the corresponding tenantConfig object, and an error if there is any.
func (c *FakeTenantConfigs) Get(name string, options v1.GetOptions) (result *danmv1.TenantConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tenantconfigsResource, name), &danmv1.TenantConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*danmv1.TenantConfig), err
}

// List takes label and field selectors, and returns the list of TenantConfigs that match those selectors.
func (c *FakeTenantConfigs) List(opts v1.ListOptions) (result *danmv1.TenantConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tenantconfigsResource, tenantconfigsKind, opts), &danmv1.TenantConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &danmv1.TenantConfigList{ListMeta: obj.(*danmv1.TenantConfigList).ListMeta}
	for _, item := range obj.(*danmv1.TenantConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tenantConfigs.
func (c *FakeTenantConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tenantconfigsResource, opts))
}

// Create takes the representation of a tenantConfig and creates it.  Returns the server's representation of the tenantConfig, and an error, if there is any.
func (c *FakeTenantConfigs) Create(tenantConfig *danmv1.TenantConfig) (result *danmv1.TenantConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tenantconfigsResource, tenantConfig), &danmv1.TenantConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*danmv1.TenantConfig), err
}

// Update takes the representation of a tenantConfig and updates it. Returns the server's representation of the tenantConfig, and an error, if there is any.
func (c *FakeTenantConfigs) Update(tenantConfig *danmv1.TenantConfig) (result *danmv1.TenantConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tenantconfigsResource, tenantConfig), &danmv1.TenantConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*danmv1.TenantConfig), err
}

// Delete takes name of the tenantConfig and deletes it. Returns an error if one occurs.
func (c *FakeTenantConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(tenantconfigsResource, name), &danmv1.TenantConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTenantConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tenantconfigsResource, listOptions)

	_, err := c.Fake.Invokes(action, &danmv1.TenantConfigList{})
	return err
}

// Patch applies the patch and returns the patched tenantConfig.
func (c *FakeTenantConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *danmv1.TenantConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tenantconfigsResource, name, pt, data, subresources...), &danmv1.TenantConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*danmv1.TenantConfig), err
}
