apiVersion: v1
kind: Service
metadata:
  name: vnf-external-svc
  namespace: example-vnf
  annotations:
    danm.k8s.io/selector: '{"vnf-type":"example-vnf"}'
    danm.k8s.io/network: external
spec:
  clusterIP: None
  ports:
  - name: diameter
    port: 3868
    protocol: TCP
