### K8s DanmNet template ###
apiVersion: danm.k8s.io/v1
# This is a 3rd party addition to a K8s cluster.
# A DamnNet object represents a physical network together with its resources and configuration applications can use.
# The DANM will always connect K8s pods to K8s DanmNets.
kind: DanmNet
metadata:
  # Name of the K8s DanmNet object this file represents
  # MANDATORY - STRING
  name: ## DANMNET_NAME  ##
  # The K8s namespace the network belongs to.
  # MANDATORY - STRING
  namespace: ## NS_NAME  ##
spec:
  # This parameter will be used in application description templates for referring to a desired connection point
  # Currently this parameter shall exactly match with the name of DanmNet object itself
  # MANDATORY - STRING
  NetworkID: ## NETWORK_NAME  ##
  # This parameter, if present, denotes which backend willl be used to provision the container interfaces connected to this network.
  # Currently supported values with dynamic integration level are IPVLAN (default), SRIOV, or MACVLAN.
  # - IPVLAN option results in an IPVLAN sub-interface provisioned in L2 mode, and connected to the designated host device
  # - SRIOV option pushes a pre-allocated Virtual Function of the configured host device to the container's netns
  # - MACVLAN option results in a MACVLAN sub-interface provisioned in bridge mode, and connected to the designated host device
  # For any other CNI backend DANM will read their configuration from the configured CNI config directory.
  # E.g. when a Pod is connected to a DanmNet with "NetworkType" set to "flannel", DANM will pass the content of /etc/cni/net.d/flannel.conf file to the /opt/cni/bin/flannel binary by invoking a standard CNI operation.
  # The default IPVLAN backend will be used if this parameter is not specified.
  # OPTIONAL - ONE OF {ipvlan,sriov,<NAME_OF_STATIC_LEVEL_CNI_BINARY>}
  # DEFAULT VALUE: ipvlan
  NetworkType: ## BACKEND_TYPE ##
  # Specific dynamic configuration options can be passed to the network provisioning backends.
  # Dynamic configuration is supported only for IPVLAN, and SRIOV backends.
  # Other networks are always provisioned from static configuration. Options are silently ignored if NetworkType is set to a non-dynamically integrated backend.
  Options:
    # Name of the parent host device (i.e. physical host NIC).
    # Sub-interfaces are connected to this NIC in case NetworkType is set to IPVLAN, or MACVLAN.
    # A Virtual Function belonging to this Physical Function is taken-up in case NetworkType is set to SRIOV.
    # OPTIONAL - STRING
    host_device: ## PARENT_DEVICE_NAME ##
    # Name of a network Device Plugin resource pool
    # The device_pool parameter generally represents the base resource name of the Kubernetes Devices connected to this network.
    # Specifically for DanmNets with "NetworkType: sriov" this option is mandatory, and it represents a pool of VFs Pods connecting to this network will get one provisioned from.
    # OPTIONAL - STRING
    device_pool: ## DEVICE_PLUGIN_RESOURCE_POOL_MAME ##
    # The IPv4 CIDR notation of the subnet associated with the network.
    # Pods connecting to this network will get their IPv4 IP from this subnet, if defined.
    # Only has an effect with dynamically integrated backends. Ignored for other NetworkTypes.
    # OPTIONAL - IPv4 CIDR FORMAT (e.g. "10.0.0.0/24")
    cidr: ## SUBNET_CIDR ##
    # IPv4 allocation will be done according to the narrowed down allocation pool parameter, if defined.
    # Allocation pool must be provided together with "cidr", and shall be included in the subnet range.
    # Only has an effect with dynamically integrated backends. Ignored for other NetworkTypes.
    allocation_pool:
      start: ## FIRST_ASSIGNABLE_IP ##
      end: ## LAST_ASSIGNABLE_IP ##
    # The IPv6 CIDR notation of the subnet associated with the network.
    # Pods connecting to this network will get their IPv6s from this subnet, if defined.
    # Only has an effect with dynamically integrated backends. Ignored for other NetworkTypes.
    # OPTIONAL - IPv6 CIDR FORMAT (e.g. "2001:db8::/45")
    net6: ## SUBNET_CIDR ##
    # Interfaces connected to this network will be renamed to "container_prefix" inside the container.
    # If not provided, DANM will dynamically allocate a name for each container interface belonging to this network in Pod instantiation time.
    # Generally supported parameter, works with all NetworkTypes.
    # Do not specify container_prefix in case multiple interfaces are provisioned from the same DanmNet.
    # OPTIONAL - STRING
    container_prefix: ## INTERNAL_IF_NAME ##
    # Policy-based IP routes belonging to this network will be installed in this routing table, if a Pod asks for them.
    # Generally supported parameter, works with all NetworkTypes.
    # OPTIONAL - INTEGER (e.g. 201)
    rt_tables: ## HOST_UNIQUE_ROUTING_TABLE_NUMBER ##
    # IPv4 routes to be installed into the default routing table of all Pods connected to this network.
    # Generally supported parameter, works with all NetworkTypes.
    # OPTIONAL - LIST OF DESTINATION_IPV4_CIDR:IPV4_GW ENTRIES (e.g. "10.20.0.0/24: 10.0.0.1")
    routes:
      ## IP_ROUTE_1 ##
      ## IP_ROUTE_2 ##
    # IPv6 routes to be installed into the default routing table of all Pods connected to this network.
    # Generally supported parameter, works with all NetworkTypes.
    # OPTIONAL - LIST OF DESTINATION_IPV6_CIDR:IPV6_GW ENTRIES
    routes6:
      ## IP_ROUTE_1 ##
      ## IP_ROUTE_2 ##
    # If this parameter is present then traffic going through this network will be VxLAN tagged with the provided identifier
    # The VxLAN tag shall be unique on the level of the underlying host.
    # Management of the VxLAN interface is handled automatically by DANM. Provisioning is generally supported for all NetworkTypes.
    # Only IPVLAN, and MACVLAN interfaces will be automatically connected to the provisioned VxLAN.
    # OPTIONAL - INTEGER (e.g. 50)
    vxlan: ## VXLAN_TAG ##
    # If this parameter is present then traffic going through this network will be VLAN tagged with the provided identifier
    # The VLAN ID shall be unique on the level of the underlying host.
    # Management of the VLAN interface is handled automatically by DANM. Provisioning is generally supported for all NetworkTypes.
    # Only dynamically supported NetworkType interfaces will be automatically connected to the provisioned VLAN.
    # VLAN and VxLAN paramaters are mutually exclusive! Defining both in the same DanmNet will result in a validation error!
    # OPTIONAL - INTEGER (e.g. 4000)
    vlan: ## VLAN_TAG ##
