# API version of the specific K8s object
# MANDATORY - STRING
apiVersion: ## API_VERSION ##
# The type of the K8s object wished to be created.
# MANDATORY - STRING
kind: ## DaemonSet, Deployment, StatefulSet ... ##
metadata:
  # Name of the K8s object this file represents
  # MANDATORY - STRING
  name: ## OBJECT_NAME  ##

  # The K8 namespace the object belongs to.
  # DanmNets and TenantNetworks are namespaced resources, so a Pod can only connect to a DanmNet/TenantNetwork if it resides in the same namespace.
  # MANDATORY - STRING
  namespace: ## NS_NAME  ##

spec:
  # The specification body of the K8s object according to its default K8s API schema
  # MANDATORY
  template:
    metadata:
      annotations:
      # DANM shall be driven with networking related requirements stated in this JSON formatted field.
      # Each entry listed in danm.k8s.io/interfaces annotation results in a network interface provisioned into every Pod's network namespace created based on this template.
      # The interface is provisioned via the backend specified in the referenced network object (or with DANM's in-built IPVLAN CNI by default).
      # MANDATORY - LIST OF REQUIRED NETWORK INTERFACES
      #   One network connection can have the following attributes:
      #   EXACTLY ONE OF THE FOLLOWING NETWORK IDENTIFIER OPTIONS:
      #   OPTION1: "network": Name of the DanmNet (i.e. ObjectMeta.Name) to which the interface should be connected to.
      #   OPTION2: "tenantNetwork": Name of the TenantNetwork (i.e. ObjectMeta.Name) to which the interface should be connected to.
      #   OPTION3: "clusterNetwork": Name of the ClusterNetwork (i.e. ObjectMeta.Name) to which the interface should be connected to.
      #   "ip": desired IPv4 address assigment scheme.
      #     Mandatory for connecting to networks with dynamic NetworkTypes, such as IPVLAN, MACVLAN, or SR-IOV.
      #     Optional for static NetworkTypes. When "ip" is defined for a static network also having Spec.Options.Cidr set, the "ipam" section of its static CNI config file is overwritten by DANM IPAM.
      #     OPTIONAL PARAMETER
      #     Possible values:
      #     - "dynamic": the first free IPv4 address is dynamically allocated from the referenced network's allocation pool
      #     - "## DESIRED_STATIC_IPV4_ADDR_FROM_CIDR (e.g. "10.10.0.101") ##"
      #     - "none": no IPv4 is allocated to the interface
      #   "ip6": desired IPv6 address assigment scheme.
      #     Mandatory for connecting to networks with dynamic NetworkTypes, such as IPVLAN, MACVLAN, or SR-IOV.
      #     Optional for static NetworkTypes. When "ip6" is defined for a static network also having Spec.Options.Net6 set, the "ipam" section of its static CNI config file is overwritten by DANM IPAM.
      #     OPTIONAL PARAMETER
      #     Possible values:
      #     - "dynamic": the first free IPv6 address is dynamically allocated from the referenced network's V6 allocation pool
      #     - "## DESIRED_STATIC_IPV6_ADDR_FROM_NET6 (e.g. "2a00:8a00:a000:1193::03e:2002") ##"
      #     - "none": no IPv6 address is allocated to the interface
      #   "proutes": list of policy-based IPv4 routes to be added to the configured routing table of this interface.
      #     Generally supported parameter, works with all NetworkTypes.
      #     OPTIONAL PARAMETER
      #     possible value: {"DESTINATION_IPV4_CIDR1":"IPV4_GW1","DESTINATION_IPV4_CIDR2":"IPV4_GW2"...}
      #   "proutes6": list of policy-based IPv6 routes to be added to the configured routing table of this interface.
      #     Generally supported parameter, works with all NetworkTypes.
      #     OPTIONAL PARAMETER
      #     possible value: {"DESTINATION_IPV6_CIDR1":"IPV6_GW1","DESTINATION_IPV6_CIDR2":"IPV6_GW2"...}
        danm.k8s.io/interfaces: |
          [
            {
              "network":"<NETWORK1_NAME>",
              "ip": "<ALLOCATION_SCHEME>",
              "<OTHER_OPTION>": "<OPTION_VALUE>",
              ...
            },
            {
              "tenantNetwork":"<NETWORK2_NAME>",
              "ip": "<ALLOCATION_SCHEME>",
              "<OTHER_OPTION>": "<OPTION_VALUE>",
              ...
            },
            {
              "clusterNetwork":"<NETWORK3_NAME>",
              "ip": "<ALLOCATION_SCHEME>",
              "<OTHER_OPTION>": "<OPTION_VALUE>",
              ...
            }
          ]
  ...
  spec:
    containers:
    - name:
    ...
      resources:
        # Network Device Plugin managed resources (e.g. devices/interfaces) to be requested for DanmNets.
        # OPTIONAL PARAMETER - but MANDATORY if a network Device Plugin is being used for provisioning the network, e.g. for SR-IOV backend
        requests:
          "<DEVICE_PLUGIN_RESOURCE_POOL_NAME_A>": "<NUM_OF_RESOURCES>"
          "<DEVICE_PLUGIN_RESOURCE_POOL_NAME_B>": "<NUM_OF_RESOURCES>"
          ...
        # OPTIONAL PARAMETER - but MANDATORY if a network Device Plugin is being used for provisioning the network, e.g. for SR-IOV backend
        limits:
          "<DEVICE_PLUGIN_RESOURCE_POOL_NAME_A>": "<NUM_OF_RESOURCES>"
          "<DEVICE_PLUGIN_RESOURCE_POOL_NAME_B>": "<NUM_OF_RESOURCES>"
          ...
  ...
