apiVersion: v1
kind: Config
current-context: default
clusters:
- cluster:
    certificate-authority-data: ${CLUSTER_CA_CERTIFICATE}
    server: ${CLUSTER_SERVER}
  name: ${CLUSTER_NAME}
contexts:
- context:
    cluster: ${CLUSTER_NAME}
    user: danm
  name: default
users:
- name: danm
  user:
    token: ${SERVICEACCOUNT_TOKEN}
preferences: {}
