/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterNetworkListerExpansion allows custom methods to be added to
// ClusterNetworkLister.
type ClusterNetworkListerExpansion interface{}

// DanmEpListerExpansion allows custom methods to be added to
// DanmEpLister.
type DanmEpListerExpansion interface{}

// DanmEpNamespaceListerExpansion allows custom methods to be added to
// DanmEpNamespaceLister.
type DanmEpNamespaceListerExpansion interface{}

// DanmNetListerExpansion allows custom methods to be added to
// DanmNetLister.
type DanmNetListerExpansion interface{}

// DanmNetNamespaceListerExpansion allows custom methods to be added to
// DanmNetNamespaceLister.
type DanmNetNamespaceListerExpansion interface{}

// TenantConfigListerExpansion allows custom methods to be added to
// TenantConfigLister.
type TenantConfigListerExpansion interface{}

// TenantNetworkListerExpansion allows custom methods to be added to
// TenantNetworkLister.
type TenantNetworkListerExpansion interface{}

// TenantNetworkNamespaceListerExpansion allows custom methods to be added to
// TenantNetworkNamespaceLister.
type TenantNetworkNamespaceListerExpansion interface{}
