apiVersion: v1
kind: Service
metadata:
  name: vnf-internal-processor
  namespace: example-vnf
  annotations:
    danm.io/selector: '{"app":"internal-processor"}'
    danm.io/network: internal
spec:
  clusterIP: None
  ports:
  - name: zeromq
    port: 5555
    protocol: TCP
