# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-client
  namespace: external-client
spec:
  selector:
    matchLabels:
      app: external-client
  replicas: 1
  template:
    metadata:
      labels:
        app: external-client
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"network":"external", "ip":"dynamic"}
          ]
    spec:
      containers:
      - name: busybox
        imagePullPolicy: IfNotPresent
        image: busybox:latest
        args:
        - sleep
        - "1000"
