# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-processor
  namespace: example-vnf
spec:
  selector:
    matchLabels:
      app: internal-processor
  replicas: 6
  template:
    metadata:
      labels:
        app: internal-processor
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"network":"management", "ip":"dynamic"},
            {"network":"internal", "ip":"dynamic"}
          ]
    spec:
      containers:
      - name: busybox
        imagePullPolicy: IfNotPresent
        image: busybox:latest
        args:
        - sleep
        - "1000"
