# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: danm.k8s.io/v1
kind: TenantConfig
metadata:
  name: wrong-tconf
hostDevices:
- name: ens4
  vniType: vlan
networkIds:
  flannel: flannel