apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deployment
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"tenantNetwork":"management", "clusterNetwork":"external", "ip":"dynamic"}
          ]
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        args:
        - sleep
        - "1000"